import ProjectDescription

let workspace = Workspace(
    name: "AccountBook",
    projects: ["Projects/**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
